### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [cscherrer/Soss.jl#252]
The most recent version of Soss that is available in the registry is 0.16.2 (https://github.com/JuliaRegistries/General/blob/master/S/Soss/Versions.toml) even though the current version in Project.toml is 0.19.0. Is it possible to register 0.19.0 (and maybe the other releases missing in the registry)?

**Comment by mschauer** [comment]
Automerge requires version increments as one of 0.0.1, 0.1.0, 1.0.0

**Comment by DilumAluthge** [comment]
We can manually merge a PR where the version increment isn't one of those. Just comment saying that the version number is intentional, and someone will manually merge it.

**Comment by cscherrer** [comment]
Hi @devmotion , thanks for pointing this out.

The story behind this is that we had some big changes that basically broke everything. So most of the time since the last release has been fixing those things, adding more functionality, and "wait, no that's not right". We wanted to get things reasonably working again before making a new release. At the same time, we're using @DilumAluthge 's [VersionVigilante](https://github.com/bcbi/VersionVigilante.jl), so we want it to be happy. 

I think we can do a release now, but I don't think it makes sense to release the intermediate mostly-broken steps along the way. I guess our choices are to have a big jump, or we could just go back to 0.17.0. In that last option, the git history would look weird, but the release schedule (which is much more visible) would be just fine.

I'm open for suggestions on the best way to handle this :)

**Comment by cscherrer** [comment]
Ok, I did the rewind thing, so we'll have a v0.17.0 soon:
https://github.com/JuliaRegistries/General/pull/33931

I'll close this now, thanks @devmotion @DilumAluthge
